#!/usr/bin/env bash
# Builds the macOS app icon from the mobile app's 1024x1024 source, so the artwork lives in
# exactly one place (apps/mobile/assets/icon.png — already the icon on iOS and Android) instead
# of a second binary copy committed here that quietly drifts from it.
#
# sips and iconutil are stock macOS; this package only targets macOS, so that is not a new
# constraint. The output is git-ignored: it is a build artifact, regenerated by `pnpm build`.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
src="$here/../../mobile/assets/icon.png"
out_dir="$here/../build"
iconset="$out_dir/icon.iconset"

if [ ! -f "$src" ]; then
  echo "make-icns: source icon not found at $src" >&2
  exit 1
fi

rm -rf "$iconset"
mkdir -p "$iconset"

# The names are load-bearing: iconutil only accepts this exact set of files.
for size in 16 32 128 256 512; do
  sips -z "$size" "$size" "$src" --out "$iconset/icon_${size}x${size}.png" >/dev/null
  sips -z $((size * 2)) $((size * 2)) "$src" --out "$iconset/icon_${size}x${size}@2x.png" >/dev/null
done

iconutil -c icns "$iconset" -o "$out_dir/icon.icns"
rm -rf "$iconset"
echo "make-icns: wrote $out_dir/icon.icns"
